apiVersion: v1
kind: Pod
metadata:
  name: candy-service-pod
spec:
  containers:
  - name: candycontainer
    image: linuxacademycontent/candy-service:1
    volumeMounts:
    - name: config-volume
      mountPath: /etc/candy-service/candy.cfg


  volumes:
  - name: config-volume
    configMap:
      name: candy-service-config


#     There is some configuration data the container will need:
# candy.peppermint.power=100000000
# candy.nougat-armor.strength=10
# It will expect to find this data in a file at /etc/candy-service/candy.cfg. Store the configuration data in a ConfigMap called candy-service-config and provide it to the container as a mounted volume.