apiVersion: v1
kind: Pod
metadata:
  name: my-securitycontext-pod
spec:
  securityContext:
    runAsUser: 2000
    fsGroup: 3000
  containers:
  - name: myapp-container
    image: busybox
    command: ['sh', '-c', "cat /message/message.txt && sleep 3600"] # file is at new /message directory 
    volumeMounts:
    - name: message-volume
      mountPath: /message # what the volume dir will mount to in the container 
  volumes:
  - name: message-volume
    hostPath:
      path: /etc/message # where the directory is on the host(s)